name: Test

on:
  workflow_dispatch:

jobs:
  style:
    name: Check Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Check Style
        run: cargo fmt --all --check

  test:
    name: Test
    needs: style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: JMAP Protocol Tests
        run: cargo test -p stalwart-lite jmap_proto:: -- --nocapture

      - name: IMAP Protocol Tests
        run: cargo test -p stalwart-lite imap_proto:: -- --nocapture

      - name: Full-text search Tests
        run: cargo test -p stalwart-lite store:: -- --nocapture

      - name: Workspace Tests
        run: cargo test --workspace
